### ISSUE TITLE
Add face selection (select one face that will not be blur)

### ISSUE THREAD

**Issue by Katsuryoku** [animikhaich/Real-Time-Face-Anonymizer#5]
In GDPR, another line is the possibility that: a person can request a video with only their face visible. Do you think it is possible to implement it in your software?

**Comment by animikhaich** [comment]
Yes. That can be done with the help of Facial Recognition. It is not implemented in this particular project of mine, but I have implemented something similar here: https://github.com/animikhaich/Facial-Recognition-Dashboard

References: https://github.com/rcmalli/keras-vggface
